### ISSUE TITLE
Make Client Timeout Configurable

### ISSUE THREAD

**Issue by boldtrn** [zileo-net/logback-logdna#10]
Thanks for providing this great library. One issue I have seen recently with this client and Logdna is that I get frequent timeouts.

`net.zileo.logback.logdna.LogDnaAppender: Error calling LogDna : java.net.ConnectException: Connection timed out (Connection timed out)
` 

Since my servers are located in Europe, this might be the reason for seeing the time out. So I'd like to try to configure the time out.

**Comment by jlannoy** [comment]
Hello @boldtrn. I made the requested change. Along with a new CI-integrated project, better tests and coverage, but now Java-11 based. I released it under the 1.1.0 version.

Pay attention that it doesn't rely by default on Jersey, you need to provide a Jax-RS client yourself in your pom. If it was not the case before, you will need to add these dependencies : 

```xml        
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.31</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.31</version>
            <scope>test</scope>
        </dependency>
```

BUT I'm not sure it will help. I've had the same problem as you, with EU located server... I hardly thought we had this problem in july once LogDna had availability problem. When reading the doc and making the change, I read that if not configured, the webclient timeout was 0 and considered as infinite. So I'm not sure the timeout was really piloted by the webclient in the appender (and not by some other inner components...). We will see.

**Comment by boldtrn** [comment]
Thanks so much for taking on this task @jlannoy! Unfortunately, the project where I am using the logger is still on Java 8. We are looking at upgrading but this might be still a bit down the road.

BTW: Is there a reason to upgrade to Java 11? I mean: as a library that is used by other projects, having a lower Java level increases usage.

**Comment by jlannoy** [comment]
I hardly think that projects should move from Java 8 asap. Oracle has dropped commercial support till January 2019, and will drop it for personal use in December 2020. AdoptOpenJDK will support it until 2026, but it's more for maintenance...

But it's not the real reason. You may have noticed I have put in place a real CI/CD environment, with build, test and release management, but also integrated with Sonar, for test coverage and other fancy things. Sonar also announced the drop of Java 8 support, this is why I migrated the library to Java 11. I've seen a lot of open source projects doing the same, I read a little bit about it, and took that decision.

I'll see today if I can release a specific version of the library for java 8 (as it doesn't use anything special). I had to try a new one, as I've rewritten the documentation with AsciiDoc.

**Comment by boldtrn** [comment]
Thanks a lot @jlannoy! 

To provide a bit more background:
We use JDK 13 to build the project, but we have set the build target to 8. We are simply not using any language features that would require to switch to a different build target. I am not sure, how big the benefits are to switch the build target, if you don't use the language features? Not sure if you have read anything about that?

With build target 8, we still benefit from all the improvements of the JVM from 8 to 13, like improved GC, etc.

**Comment by jlannoy** [comment]
The more important is... What are your deployment requirements ? Do you have an application server (external), an embedded server, or is it a JAR where only need one JDK to run it ?

In first and second cases, you're dependent of the server used, and see how their version goes with java 8/11. If you are on your own, I think there is not huge benefits for a migration of an existing project. On a dev side for small projects, improvements are new useful methods on the stream, strings and date APIs (for example) ; but I mainly discovered them when needed. On the run side there are performance and security optimizations, like a new GC. Pay attention you __don't__ benefit of (some of) these improvements if you build with a JDK 13 but run on a JVM 8... I'm pretty sure the GC is related to the version of the JVM you use to run, not to build.

**Comment by boldtrn** [comment]
Yes exactly. GC for example was a big point for us and a major reason to update the JVM. We definitely benefit from that. We are building fat jars that are deployed with a JDK, so luckily we don't have an external application server :).

**Comment by jlannoy** [comment]
I tried to go back to Java 8. Although it works, I get this warning on Sonar : 
_The version of Java installed in the scanner environment should be upgraded to at least Java 11 by October 2020. Pre-11 versions of Java are already deprecated and scanners using them will stop functioning after October 2020. This refers specifically to the JDK or JRE installed and used in the context where your SonarCloud scanner analysis tool is running._

I want to keep the Sonar analysis. I'm checking if I can keep Java 8 release with Java 11 analysis for Sonar. But if it's too complicated I'll just move the library to Java 11.

**Comment by jlannoy** [comment]
There it is ; I've setup a second build phase for Java 11 + Sonar... I think it's acceptable as this library is very small. A version **1.1.1** has been released ; with a new documentation page.

**Comment by boldtrn** [comment]
Thanks a lot for the changes. I had the chance to actually try this in production now. Unfortunately we still see timeouts from LogDNA. I have been in contact with their support as well, but they blame the connection links between Europe and the US.

In any case, thanks so much for your support @jlannoy!

**Comment by jlannoy** [comment]
Yes, I've the same problem as you. But I'm using LogDNA for 3 years now... I'm sure this problem is rather new (some month). :-(

**Comment by boldtrn** [comment]
Yes, I made the same observation. I think it started anywhere between April and June.
