### ISSUE TITLE
Android instanciation problem

### ISSUE THREAD

**Issue by jlannoy** [zileo-net/logback-logdna#28]
_(Received)_

Hi Jonathan,
 
I’m working on an android app and trying to use your log dna appender.  I’m getting an initialization error:
 
2021-02-18 08:05:01.341 13359-13359/com.Rom3Dev.PatientApp.qa I/System.out: 08:05:01,024 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [net.zileo.logback.logdna.LogDnaAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type net.zileo.logback.logdna.LogDnaAppender
2021-02-18 08:05:01.341 13359-13359/com.Rom3Dev.PatientApp.qa I/System.out:         at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type net.zileo.logback.logdna.LogDnaAppender
2021-02-18 08:05:01.343 13359-13359/com.Rom3Dev.PatientApp.qa I/System.out:     at                at net.zileo.logback.logdna.LogDnaAppender.identifyHostname(LogDnaAppender.java:97)
2021-02-18 08:05:01.343 13359-13359/com.Rom3Dev.PatientApp.qa I/System.out:     at                at net.zileo.logback.logdna.LogDnaAppender.<init>(LogDnaAppender.java:80)
2021-02-18 08:05:01.343 13359-13359/com.Rom3Dev.PatientApp.qa I/System.out: 08:05:01,025 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@3:81 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback
 
 
I’m not sure what hostname it is trying to resolve. 
 
My logback entries for this appender  (I also tried with System.setProperty())
```xml
<configuration>
    <appender name="LogDnaHttp" class="net.zileo.logback.logdna.LogDnaAppender">
        <encoder>
            <pattern>%d{MMM dd HH:mm:ss} %-5level %m%n</pattern>
        </encoder>
        <appName>RomTech Patient App</appName>
        <ingestUrl>"https://logs.logdna.com/logs/ingest"</ingestUrl>
        <ingestKey>"xxxxxxxxxxxxxxxxxx"</ingestKey>
<!--        <ingestUrl>${LOGDNA_INGEST_URL}</ingestUrl>-->
<!--        <ingestKey>${LOGDNA_INGEST_KEY}</ingestKey>-->
<!--        <mdcFields>requestId,requestTime</mdcFields>-->
<!--        <mdcTypes>string,int</mdcTypes>-->
<!--        <tags>dev</tags>-->
        <connectTimeout>5000</connectTimeout>
        <readTimeout>10000</readTimeout>
    </appender>

    <appender name="LogDna" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="LogDnaHttp" />
        <queueSize>500</queueSize>
        <discardingThreshold>0</discardingThreshold>
        <includeCallerData>false</includeCallerData>
    </appender>
```
 
My gradle dependencies:
```
implementation('org.glassfish.jersey.core:jersey-client:2.31') {
    exclude group: "jakarta.ws.rs", module:  "*"
}
implementation('net.zileo:logback-logdna:1.1.1') {
    exclude group: "ch.qos.logback", module: "*"
}
```
 
if you see a quick fix please let me know
 
Thanks,
Mark

**Comment by jlannoy** [comment]
Hi Mark.

The hostname it tries to resolve is the local one, the goal is to try to detect the server URL and saves it in the logs. It's rather simple : 

```java
    private String identifyHostname() {
        try {
            return InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException e) {
            return "localhost";
        }
    }
```

I would assume from what you are telling that the `InetAddress.getLocalHost()` do simply not work on Android. Before I can make any modification, would you please try to put this code in an Android app and execute it, to check what exception we got ?

```java
        try {
            return InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            e.printStackTrace();
        }
```

**Comment by markbeifuss** [comment]
I was doing that as I got this... let me see what it does, throws an exception (android.os.NetworkOnMainThreadException)

**Comment by markbeifuss** [comment]
W/System.err: android.os.NetworkOnMainThreadException
W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/System.err:     at java.net.InetAddress.getLocalHost(InetAddress.java:1488)
W/System.err:     at com.Rom3Dev.PatientApp.util.Rom3LogManager.<clinit>(Rom3LogManager.java:85)
W/System.err:     at com.Rom3Dev.PatientApp.util.Rom3LogManager.d(Rom3LogManager.java:102)
W/System.err:     at com.Rom3Dev.PatientApp.MainActivity.onCreate(MainActivity.java:145)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7957)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7946)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err:     at android.os.Looper.loop(Looper.java:237)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8107)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by jlannoy** [comment]
OK, it seems like a security exception ; like if the network operation are blocked in your Android environment.

Let me some hours, and I'll release a new version with an option allowing to disable that local network address identification. Then you'll tell me if it works :)

**Comment by markbeifuss** [comment]
Thanks,  Here are the relevant permissions:
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

**Comment by markbeifuss** [comment]
<uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

**Comment by markbeifuss** [comment]
Found that  strictmode was generating the exception when calling getlocalhost().  Initializing the log manager in a separate thread seems to have fixed the getlocalhost exception.

**Comment by markbeifuss** [comment]
Hi Jonathan,

Wanted to ping you about something else I’m seeing.  We are using neverBlock true and with a queueSize of 500 we are losing some messages however we only have about 125 give or take messages in a session where I disconnect the tablet from the internet for a period of time and then restore the connection.  If I set the queueSize to 2500 then I don’t lose any messages.  It looks to me that the queueSize is the number of messages that can be held by the blockingQueue so I’m a bit confused.  Have any idea on why that is?



My relevant logback.xml  (PAPERTRAIL is just a marker)

    <appender name="LogDnaHttp" class="com.Rom3Dev.PatientApp.util.LogDnaAppender">
        <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
            <evaluator class="ch.qos.logback.classic.boolex.OnMarkerEvaluator">
                <marker>PAPERTRAIL</marker>
            </evaluator>
            <onMismatch>DENY</onMismatch>
        </filter>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%d{MMM dd HH:mm:ss.SSS} %-5level %m%n</pattern>
        </layout>
        <appName>${APP_NAME}</appName>
        <ingestUrl>${LOGDNA_INGEST_URL}</ingestUrl>
        <ingestKey>${LOGDNA_INGEST_KEY}</ingestKey>


        <tags>${APP_NAME}</tags>
        <connectTimeout>5000</connectTimeout>
        <readTimeout>10000</readTimeout>
    </appender>

    <appender name="LogDna" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="LogDnaHttp" />
        <queueSize>500</queueSize>
        <discardingThreshold>0</discardingThreshold>
        <maxFlushTime>10000</maxFlushTime>
        <includeCallerData>false</includeCallerData>
        <neverBlock>true</neverBlock>
    </appender>



Thanks,
Mark

**Comment by jlannoy** [comment]
Hi @markbeifuss.
Sorry for delay, but as you were not facing the problem anymore I took some more times. Now in version **1.1.2** you can specify the hostname yourself via the `<hostname>` parameter, if you want to avoid a INetAddress lookup. 
Jonathan
